apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    # path to the folder with the YAML manifests
    path: manifests
    repoURL: https://github.com/ramirezalfredo/nginx-alpine
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}