apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    # path to the folder with the YAML manifests
    path: nginx-deployment
    repoURL: https://github.com/ramirezalfredo/nginx-alpine
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}